### ISSUE TITLE
replacement with blank string isn't possible (sort of)

### ISSUE THREAD

**Issue by werelord** [flytam/filenamify#3]
In my use case, I just want to remove all invalid characters from the string, but I am unable to due to the default being `!`; the code checks `Replacement == ""` and sets it to default if the replacement string is blank.

Fixing this isn't possible under the original methods, but with the V2 methods it is with some changes; the V2 methods can change the options after the default has been with calling the option function.  I've engineered a fix under said V2 methods; you can find the changes [here](https://github.com/werelord/filenamify/tree/blank_replacement).  In short, the changes are:

- moved the logic out of the original methods into the "V2" methods (original call V2, instead of V2 calling original)
- V2 changes the default options via passed in methods
- remove check for `replacement == ""`
- Tests:
  - original methods remains the same (just enhanced the output on test case failure)
  - V2 method, check on empty options list
  - V2 method, test blank string replacement

Thoughts?  If you want me to create a pull request with these changes, let me know..

**Comment by flytam** [comment]
@werelord LGTM. I think the change is ok, you can create a pull request when you r available
