### ISSUE TITLE
Filenames like `com2.txt`, `nul.bmp` are forbidden by Windows, seemingly allowed by this library

### ISSUE THREAD

**Issue by shunf4** [flytam/filenamify#8]
Filenames like `com2.txt`, `nul.bmp` are forbidden by Windows, but are seemingly allowed by this library.

This may help:

https://github.com/golang/go/blob/b8ac61e6e64c92f23d8cf868a92a70d13e20a124/src/internal/safefilepath/path_windows.go#L88

**Comment by flytam** [comment]
thanks for feedback, this library is expected to process only file names and not extensions. windows related is supported(just updated the testcase)
<img width="757" alt="image" src="https://github.com/flytam/filenamify/assets/20512530/06657f65-b451-4994-a7b2-5d2dac161951">
